
server.port=8888
upload.path=C:/files/

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/upload_file?currentSchema=upload
spring.jpa.properties.hibernate.default_schema=upload
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.initialization-mode=always

spring.ldap.embedded.ldif=classpath:test-ldap.ldif
spring.ldap.embedded.base-dn=dc=springframework,dc=org
spring.ldap.embedded.port=8389 

spring.thymeleaf.mode= LEGACYHTML5
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
