
server.port=8888

#spring.ldap.embedded.ldif=classpath:test-ldap.ldif
#spring.ldap.embedded.base-dn=dc=springframework,dc=org
#spring.ldap.embedded.port=8389



upload.path=C:/files/

spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/upload_file?currentSchema=upload
spring.jpa.properties.hibernate.default_schema=upload
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.liquibase.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect

#spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.initialization-mode=always

#application.ldap.domain=domain
#application.ldap.url=ldap://domain.corp:3268/dc=root,dc=branch
#application.ldap.rootDn=ou=users,ou=mnt
spring.ldap.embedded.ldif=classpath:test-ldap.ldif
spring.ldap.embedded.base-dn=dc=springframework,dc=org
spring.ldap.embedded.port=8389 

#spring.customized.suite.auth_type = ${AUTH_TYPE:ldap}
#spring.ldap.url =${LDAP_URLS:ldap://ldap.domain.com}
#spring.ldap.base=${LDAP_BASE:dc=dc,dc=com}

