
server.port=8888

upload.path.regular =/app/airflow/dags
upload.path.confidential =/app/airflow/scripts/

#multipart.maxFileSize=-1
#multipart.maxRequestSize=-1

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/upload_file?currentSchema=upload
spring.jpa.properties.hibernate.default_schema=upload
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.initialization-mode=always
#spring.jpa.properties.hibernate.id.new_generator_mappings=false

spring.ldap.embedded.ldif=classpath:user-ldap.ldif
spring.ldap.embedded.base-dn=dc=springframework,dc=org
spring.ldap.embedded.port=8389

spring.thymeleaf.mode= LEGACYHTML5
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/

spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB

#logging.level.root=trace
#logging.level.org.springframework.web=trace
#logging.level.org.hibernate=trace

ldap.connection.url=ldap://localhost:8389/dc=springframework,dc=org


#LDAP user group authorization configuration
ldap.group.role.attribute=cn
ldap.group.role.prefix=ROLE_
ldap.group.role.filter=member={0}


allowed.file.content.types=".py, .jpg, .rar, .jar"


